commerce_invoice.commerce_invoice_type.*:
  type: config_entity
  label: 'Invoice type'
  mapping:
    label:
      type: label
      label: 'Label'
    id:
      type: string
      label: 'Machine-readable name'
    description:
      type: text
      label: 'Description'
